export const description = `Do more with Galaxy AI on the most epic Galaxy yet. Wondering where the cool museum that your favorite influencer visited is located? Simply Circle to Search* with Google and start planning your own trip to the Louvre. Then get ready to experience local flavors by calling ahead with Live Translate* to make a reservation in French, even if all you know is “bonjour.” Capture every detail of your candlelit meal with impressive Nightography and zoom in to see the live violinist playing across the room. Once you’re back in your hotel room, elevate your pics from good to great right on your Galaxy S24 Ultra. You can even use your built-in S Pen to add fun doodles before posting. Unleash new ways to create, connect and more with Galaxy AI on Galaxy S24 Ultra. Epic, just like that.
Circle it, search it*, find it. Just like that. What’s your favorite influencer wearing? Where’d they go on vacation? What’s that word mean? Don’t try to describe it —use Circle to Search with Google* and get the answer in a snap. With Galaxy S24 Series, simply circle it on your screen to learn more.
Break down barriers to language barriers. Speak foreign languages on the spot using Live Translate* with Galaxy AI. Unlock the power of convenient communication with near-real-time voice translations right through your Samsung Phone app.
Note smarter, not harder. Focus on capturing your notes and spend less time perfecting them. Note Assist* with Galaxy AI will summarize, format and even translate them for you. All your notes are organized neatly so you can find what you need when you need it.
Bring details out of the darkness. Brighten up your night using Nightography Zoom with Galaxy AI on Galaxy S24 Ultra. Want a closer look? Zoom in from a distance, even in low light.
Take a great photo. Then make it better. Turn every photo into a post-worthy masterpiece. Move or remove objects. Fill in empty space. Simply snap a pic, and then take it from great to jaw-dropping with Generative Edit* powered by Galaxy AI.
What you see is what you get. Create crystal-clear content worth sharing with Galaxy S24 Ultra. From a bustling cityscape to a serene landscape, capture a masterpiece of detail with the 200MP camera and let Galaxy S24 Ultra adjust each hue and shade to reflect the world as you see it. 
Our most powerful Galaxy smartphone yet. Jump seamlessly between apps without the wait and see content in high quality with our fastest processor yet —Snapdragon®8Gen 3 for Galaxy*.
Bend time with Instant Slow-Mo*. Sometimes memories are best played in slow motion. Using Instant Slow-Mo* with Galaxy AI, you can relive any moment in epic slow motion. Just tap and hold.
Put your best text forward. Say the right thing at the right time in no time using Chat Assist* with Galaxy AI on Galaxy S24 Series. Get real-time tone suggestions to make your writing sound more professional or conversational. Plus, make typos a thing of the past. Focus on what you want to say and let Chat Assist handle the rest.
Game and stream, edge to edge. Take your streaming and gaming to the edge with Galaxy S24 Ultra. Whether you’re watching, winning or even writing, the brighter, flatter screen gives you more room to do what you love. 
Transcript Assist* takes the notes for you. Be present in meetings and let Transcript Assist* with Galaxy AI* do the hard work of taking notes for you. It creates fast and easy transcripts of recorded meetings, lectures and conversations and summarizes them instantly. Transcript Assist can even translate to other available languages, just like that.
Be lost in conversation, not translation. Wish you always had an interpreter on hand? Now you do with Galaxy AI. Simply hold up your phone during face-to-face conversations and receive real-time translations. 
LEGAL: *Requires internet connection; results may vary by uniqueness, clarity and framing of circled image and related factors. *Samsung account login required. Calls must be made using the native Samsung dialer. *For text in Samsung Notes only (200 –4,000 characters); requires Samsung account login and internet connection. *Snapdragon is a product of Qualcomm Technologies, Inc. and/or its subsidiaries. Snapdragon is a trademark or registered trademark of Qualcomm Incorporated. *Instant Slow-Mo available only with videos saved in the Samsung Gallery app, recorded at up to 4K@60 fps (not available with HDR10+ videos). *Transcript Assist available only with audio files under 3 hours and recorded using the Samsung Voice Recorder app. Summarizing feature available for text in Samsung Notes only (200-4,000 characters). Translation feature requires language preset (English and Spanish pre-installed; other languages require free download. Samsung account login and internet connection required. *Requires Samsung account log in and language preset (English and Spanish pre-installed; other languages require free download). Results may vary.`;
